# Generated by Django 3.0.6 on 2020-05-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beauty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_diary', models.TextField()),
                ('cosmetics', models.TextField()),
                ('sleep', models.IntegerField()),
            ],
        ),
    ]
